language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install:
  - composer selfupdate

install:
  - composer install --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml
  - vendor/bin/phpcs --report=full --standard=PSR2 --encoding=utf-8 src

after_script:
  - build/upload-coverage.sh

cache:
  directories:
    - vendor

notifications:
  email: jasper@future500.nl
